[workspace]
members = [
        "common",
        "dot",
        "svg",
        "gen",
        "alpha",
]
resolver="2"

[patch.crates-io]
cmd_lib = { git = "https://github.com/crzysdrs/rust_cmd_lib" }
